version: "3.9"

services:
    bankDbServer:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "Admin12345!"
            ACCEPT_EULA: "Y"
    api:
        build:
          context: .
          dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
          - "8080:80"
          - "8081:443"
        depends_on:
          - bankDbServer